### ISSUE TITLE
Build fail. ERROR: error loading package '': Encountered error while reading extension file 'protobuf_deps.bzl': no such package '@com_google_protobuf_deps//': error loading package 'external': Could not load //external package

### ISSUE THREAD

**Issue by anoopoodles** [iotaledger/compass#147]
Using Bazel version 2.1.1
Not getting no such package @io_netty_netty_tcnative_boringssl_static//jar issue
Error tracedback from this point
	File "/home/user/Projects/IOTA/compass/WORKSPACE", line 42
		maven_jars()
	File "/home/user/Projects/IOTA/compass/third-party/maven_deps.bzl", line 3, in maven_jars
		native.maven_jar
no native function or rule 'maven_jar'

and then 
ERROR: error loading package '': Encountered error while reading extension file 'protobuf_deps.bzl': no such package '@com_google_protobuf_deps//': error loading package 'external': Could not load //external package

I have added path variable in bashrc and it didnt work. First used Bazel 2.2.0 but it gave the same error , Downgraded to 2.1.1 but still the same issue persist

**Comment by karimodm** [comment]
We are aware of build issues on Compass :(. We are working on it

**Comment by efpies** [comment]
It happens because Compass's dependencies are outdated and access Maven via HTTP, which doesn't work since January, 2020. It can't be achieved without updating deps, which must be done by devs.

But we can still build it. Bazel caches dependencies, so we can fix the links in the cache. Then we need to execute the build command again.

This is how it looks on Ubuntu if you run it under the `root` user (in Docker, for example):
```bash
cd compass_src \
# The first run will fail due to the Maven URL being incorrect since January 2020
    && bazel-1.2.1 run //docker:coordinator 2>&1 || true \
# So we substitute it with a correct one in the build cache...
    && find /root/.cache/ -type f -exec sed -i "s/http:\/\/central.maven.org/https:\/\/repo1.maven.org/g" {} + \
# ...and clean the intermediate directory
    && rm -rf /root/.cache/bazel/_bazel_root/install \
# Rerun will use existing build cache and will rebuild broken packages.
# Build won't be finished successfully due to the build script downloading a docker image, which cannot be achieved
# because it's not ok to run docker inside docker. We only need an executable of the coordinator, so we copy it
# somewhere else.
    && bazel-1.2.1 run //docker:coordinator
```

`/root/.cache/bazel/_bazel_root` will be `/root/.cache/bazel/_bazel_username` in your case.

On macOS, it will be: `/private/var/tmp/_bazel_username`.

That's how I've built Compass in Ubuntu (Docker) and macOS. And it works for 4 months now.

**Comment by adeeba2** [comment]
@efpies 
This solution is not working. Idid the same changes as here. still showing the same error. how did it work?

**Comment by bhavesh197** [comment]
I am also facing the same issue. Please provide a concrete solution ASAP.

**Comment by ChiragJuyal** [comment]
> We are aware of build issues on Compass :(. We are working on it

Facing the same issue. How long will it take to get fixed? Or can you meanwhile revert the last updates so that we can use the stable version?

**Comment by GalRogozinski** [comment]
Made a PR now
